FROM golang:1.23.0-alpine AS base
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache make clang15 libbpf-dev bpftool curl git \
    musl-dev # for golangci-lint

ENV GOPATH="/go" \
    GOROOT="/usr/local/go" \
    GOPROXY="https://goproxy.io,direct" \
    PATH="${GOPATH}/bin:${GOROOT}/bin:/usr/lib/llvm15/bin:${PATH}"

RUN go install golang.org/x/tools/cmd/goimports@v0.35.0 \
    && go install mvdan.cc/gofumpt@v0.8.0 \
    && curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.62.2/golangci-lint-1.62.2-linux-amd64.tar.gz \
    | tar -xz -C /usr/local/bin --strip-components=1 golangci-lint-1.62.2-linux-amd64/golangci-lint
