name: OS Distro QEMU Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # start VMs
  qemu-vm:
    name: Start VM (${{ matrix.os }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu24.04, ubuntu22.04] # osinfo-query os

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Init QEMU
        timeout-minutes: 10
        run: |
          # Install qemu etc.
          .github/workflows/scripts/qemu-1-init.sh ${{ matrix.os }}

      - name: Start VM
        timeout-minutes: 30
        run: |
          .github/workflows/scripts/qemu-2-start.sh ${{ matrix.os }}

      - name: Test in VM
        timeout-minutes: 60
        run: |
          echo "============ Test in VM =============="
          ssh -tt \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          -o ConnectTimeout=3 \
          root@${VM_IP} "bash -s" \
          < .github/workflows/scripts/qemu-3-run.sh ${{ matrix.os }}
